### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by jeanniefinks**
- Added citation "How Well Do Sparse Imagenet Models Transfer"
- Updated citation "WoodFisher: Efficient second-order approximations for model compression"
- Added list of tutorials

### CODE REVIEW

**Review by bfineran — APPROVED** [review]
LGTM thoughts on pruning the list of tutorials to one per domain/framework?

**Review by rahul-tuli — APPROVED** [review]

**Comment by jeanniefinks** [comment]
> LGTM thoughts on pruning the list of tutorials to one per domain/framework?

Yes, I am going to group these and get a re-review. More soon.

**Comment by jeanniefinks** [comment]
Oops @bfineran this PR was not ready to merge. The tutorial list needs to be grouped.

**Comment by bfineran** [comment]
thanks PR to revert up here: https://github.com/neuralmagic/sparseml/pull/657

**Comment by bfineran** [comment]
@jeanniefinks re-opened the branch, feel free to make a new PR

**Pull request merged**
