### PR TITLE
Convert OPT MatMuls with quantized inputs to MatMulInteger

### PR DESCRIPTION
**Pull request by natuan**
This change enables converting the torch.bmm with two quantized inputs and non-quantized output to MatMulInteger. This procedure is mutually exclusive with the existing one for QATMatMul-based quantized matmuls.

The attached graph shows two MatMulInteger that are the results of this conversion on OPT-125m.
 
after

Note that the quantization of these MatMuls on OPT requires [this PR](https://github.com/neuralmagic/transformers/pull/78).

### CODE REVIEW

**Review by dbogunowicz — DISMISSED** [review]
Approving tentatively, will test it shortly.

**Comment by dbogunowicz** [comment]
Also, please update the PR description.

**Comment by natuan** [comment]
> Also, please update the PR description.

Added the description

**Review by anmarques — APPROVED** [review]
Looks good to me after the fix

**Review by bfineran — APPROVED** [review]

**Pull request merged**
