### PR TITLE
Upgrading ubuntu in workflows and setting python to 3.9

### PR DESCRIPTION
**Pull request by corey-nm**
This is necessary for upgrading to torch 1.12. Originally done in #964 , but moving these changes to a separate PR to make reviewing easier

### CODE REVIEW

**Review by rahul-tuli — APPROVED** [review]

**Review by KSGulin — COMMENTED** [review]
Thoughts of updating to ubuntu 22.04 rather than latest, so that we have a static test environment? Or do we reap more benefit from staying up to date with the latest image?

**Comment by corey-nm** [comment]
> Thoughts of updating to ubuntu 22.04 rather than latest, so that we have a static test environment? Or do we reap more benefit from staying up to date with the latest image?

Good idea, I think static test env would gain us more and be slightly easier to reproduce/debug. I'll change to 22.04

**Review by KSGulin — DISMISSED** [review]
LGTM 😃

**Comment by corey-nm** [comment]
Hmm may need to downgrade to 20.04 for package versioning. Looks like python 3.8 (keras) and 3.7 (for tf 1) aren't available via actions/setup-python.

**Review by KSGulin — APPROVED** [review]

**Review by rahul-tuli — APPROVED** [review]

**Pull request merged**
