### PR TITLE
[cherry-pick] fix propagation of mask creator objects in PT pruning modifier (#220)

### PR DESCRIPTION
**Pull request by bfineran**
fixes bug that defaults pytorch mask creators to be 'unstructured' in certain training flows

updates release version to 0.3.1 for this hotfix

### CODE REVIEW

**Comment by dhuangnm** [comment]
Can we also add a test for it so we can verify things are working?

**Comment by bfineran** [comment]
@dhuangnm the test file is updated in this PR to check that the correct mask creator is set

**Comment by dhuangnm** [comment]
> @dhuangnm the test file is updated in this PR to check that the correct mask creator is set

oh ok, cool thanks.

**Comment by dhuangnm** [comment]
Can we update the version.py to 0.3.1 for the cherry-pick?

**Review by markurtz — APPROVED** [review]

**Review by kevinaer — APPROVED** [review]

**Pull request merged**
