### PR TITLE
update:pytorch example notebooks to use manager.modify(...)

### PR DESCRIPTION
**Pull request by rahul-tuli**
Update pytorch example notebooks to use the manager.modify(...) instead of older ScheduledOptimizer(...)
fix epoch initialization to 0 instead of None

### CODE REVIEW

**Review by bfineran — COMMENTED** [review]
Looks great @rahul-tuli! Thanks for adding in the change to vision.py as well. Could you update the notebook(s) documentation to point out that `finalize()` should be called after training?

**Comment by rahul-tuli** [comment]
> Looks great @rahul-tuli! Thanks for adding in the change to vision.py as well. Could you update the notebook(s) documentation to point out that `finalize()` should be called after training?

Sure! Coming right up.

**Comment by rahul-tuli** [comment]
@bfineran Does this look okay?

**Review by bfineran — COMMENTED** [review]
looks good @rahul-tuli. let's also surround the finalize(...)s in backticks `` `finalize(...)` so they will be rendered as code

**Comment by rahul-tuli** [comment]
@bfineran, added backticks

**Review by bfineran — APPROVED** [review]

**Review by markurtz — APPROVED** [review]

**Pull request merged**
