### PR TITLE
[BugFix]: Limit torch version installed by ultralytics

### PR DESCRIPTION
**Pull request by rahul-tuli**
Currently there's a bug in our pip install sparseml[ultralytics] pathway such that it installs torch 2.0 which we do not support, when `sparseml.ultralytics.train --help` is invoked it leads to the following error (also noticed by @dhuangnm):

```bash
$ sparseml.ultralytics.train --help
Status code 429 from http://ipinfo.io/96.89.198.177/json: ERROR - 429 Client Error: Too Many Requests for url: http://ipinfo.io/96.89.198.177/json
Status code 429 from http://ipinfo.io/96.89.198.177/json: ERROR - 429 Client Error: Too Many Requests for url: http://ipinfo.io/96.89.198.177/json
Traceback (most recent call last):
  File "/home/dhuang/venv/bin/sparseml.ultralytics.train", line 5, in <module>
    from sparseml.yolov8.train import main
  File "/home/dhuang/venv/lib/python3.8/site-packages/sparseml/yolov8/train.py", line 18, in <module>
    from sparseml.yolov8.trainers import SparseYOLO
  File "/home/dhuang/venv/lib/python3.8/site-packages/sparseml/yolov8/trainers.py", line 30, in <module>
    from sparseml.pytorch.optim.manager import ScheduledModifierManager
  File "/home/dhuang/venv/lib/python3.8/site-packages/sparseml/pytorch/__init__.py", line 51, in <module>
    from .framework import detect_framework, framework_info, is_supported
  File "/home/dhuang/venv/lib/python3.8/site-packages/sparseml/pytorch/framework/__init__.py", line 24, in <module>
    from .info import *
  File "/home/dhuang/venv/lib/python3.8/site-packages/sparseml/pytorch/framework/info.py", line 26, in <module>
    from sparseml.pytorch.sparsification import sparsification_info
  File "/home/dhuang/venv/lib/python3.8/site-packages/sparseml/pytorch/sparsification/__init__.py", line 24, in <module>
    from .distillation import *
  File "/home/dhuang/venv/lib/python3.8/site-packages/sparseml/pytorch/sparsification/distillation/__init__.py", line 17, in <module>
    from .modifier_distillation import *
  File "/home/dhuang/venv/lib/python3.8/site-packages/sparseml/pytorch/sparsification/distillation/modifier_distillation.py", line 24, in <module>
    from sparseml.pytorch.sparsification.distillation.modifier_distillation_base import (
  File "/home/dhuang/venv/lib/python3.8/site-packages/sparseml/pytorch/sparsification/distillation/modifier_distillation_base.py", line 30, in <module>
    from sparseml.pytorch.sparsification.modifier import (
  File "/home/dhuang/venv/lib/python3.8/site-packages/sparseml/pytorch/sparsification/modifier.py", line 36, in <module>
    from sparseml.pytorch.utils import LOGGING_LEVELS, BaseLogger, LoggerManager
  File "/home/dhuang/venv/lib/python3.8/site-packages/sparseml/pytorch/utils/__init__.py", line 36, in <module>
    _check_torch_install()  # TODO: remove once files within package load without installs
  File "/home/dhuang/venv/lib/python3.8/site-packages/sparseml/pytorch/base.py", line 85, in check_torch_install
    return check_version("torch", min_version, max_version, raise_on_error)
  File "/home/dhuang/venv/lib/python3.8/site-packages/sparseml/base.py", line 286, in check_version
    raise ImportError(
ImportError: required max torch version 1.13.100, found 2.0.1
```

This happens due to the following line in ultralytics requirements: https://github.com/ultralytics/ultralytics/blob/441e67d3303ef6a9b0fac34fa018d20641285a33/requirements.txt#LL11C1-L11C13

The current PR overcomes this issue by limiting the torch version installed to our max supported version which is `1.13.1`

After this PR the above command runs successfully. Only caveat is that may lead to another installation of torch if versions don't match up:

```bash
sparseml.ultralytics.train --help
Status code 429 from http://ipinfo.io/96.89.198.177/json: ERROR - 429 Client Error: Too Many Requests for url: http://ipinfo.io/96.89.198.177/json
Usage: sparseml.ultralytics.train [OPTIONS]

Options:
  --recipe TEXT                   Path to recipe
  --recipe-args TEXT              json parsable dict of recipe variable names
                                  to values to overwrite with
  --resume                        resume training from last checkpoint
  --task [detect|segment|classify]
                                  Specify task to run.  [default: detect]
  --model TEXT                    i.e. yolov8n.pt, yolov8n.yaml. Path to model
                                  file  [default: yolov8n.yaml]
  --data TEXT                     i.e. coco128.yaml. Path to data file
                                  [default: coco128.yaml]
  --epochs INTEGER                number of epochs to train for  [default:
                                  100]
  --patience INTEGER              epochs to wait for no observable improvement
                                  for early stopping of training  [default:
                                  50]
  --batch INTEGER                 number of images per batch  [default: 16]
  --imgsz INTEGER                 size of input images  [default: 640]
  --save                          save checkpoints  [default: True]
  --cache                         Use cache for data loading
  --device TEXT                   cuda device, i.e. 0 or 0,1,2,3 or cpu.
                                  Device to run on
  --workers INTEGER               number of worker threads for data loading
                                  [default: 8]
  --project TEXT                  project name
  --name TEXT                     experiment name
  --exist-ok                      whether to overwrite existing experiment
  --pretrained                    whether to use a pretrained model
  --optimizer [SGD|Adam|AdamW|RMSProp]
                                  optimizer to use  [default: SGD]
  --verbose                       whether to print verbose output
  --seed INTEGER                  random seed for reproducibility  [default:
                                  0]
  --deterministic                 whether to enable deterministic mode
                                  [default: True]
  --single-cls                    train multi-class data as single-class
  --image-weights                 use weighted image selection for training
  --rect                          support rectangular training
  --cos-lr                        use cosine learning rate scheduler
  --close-mosaic INTEGER          disable mosaic augmentation for final 10
                                  epochs  [default: 10]
  --overlap-mask                  masks should overlap during training
                                  [default: True]
  --mask-ratio INTEGER            mask downsample ratio  [default: 4]
  --dropout FLOAT                 use dropout regularization  [default: 0.0]
  --lr0 FLOAT                     initial learning rate (SGD=1E-2, Adam=1E-3)
                                  [default: 0.01]
  --lrf FLOAT                     final OneCycleLR learning rate (lr0 * lrf)
                                  [default: 0.01]
  --momentum FLOAT                SGD momentum/Adam beta1  [default: 0.937]
  --weight-decay FLOAT            optimizer weight decay 5e-4  [default:
                                  0.0005]
  --warmup-epochs FLOAT           warmup epochs (fractions ok)  [default: 3.0]
  --warmup-momentum FLOAT         warmup initial momentum  [default: 0.8]
  --warmup-bias-lr FLOAT          warmup initial bias lr  [default: 0.1]
  --box FLOAT                     box loss gain  [default: 7.5]
  --cls FLOAT                     cls loss gain (scale with pixels)  [default:
                                  0.5]
  --dfl FLOAT                     dfl loss gain  [default: 1.5]
  --fl-gamma FLOAT                focal loss gamma (efficientDet default
                                  gamma=1.5)  [default: 0.0]
  --label-smoothing FLOAT         [default: 0.0]
  --nbs FLOAT                     nominal batch size  [default: 64]
  --hsv-h FLOAT                   image HSV-Hue augmentation (fraction)
                                  [default: 0.015]
  --hsv-s FLOAT                   image HSV-Saturation augmentation (fraction)
                                  [default: 0.7]
  --hsv-v FLOAT                   image HSV-Value augmentation (fraction)
                                  [default: 0.4]
  --degrees FLOAT                 image rotation (+/- deg)  [default: 0.0]
  --translate FLOAT               image translation (+/- fraction)  [default:
                                  0.1]
  --scale FLOAT                   image scale (+/- gain)  [default: 0.5]
  --shear FLOAT                   image shear (+/- deg)  [default: 0.0]
  --perspective FLOAT             image perspective (+/- fraction), range
                                  0-0.001  [default: 0.0]
  --flipud FLOAT                  image flip up-down (probability)  [default:
                                  0.0]
  --fliplr FLOAT                  image flip left-right (probability)
                                  [default: 0.5]
  --mosaic FLOAT                  image mosaic (probability)  [default: 1.0]
  --mixup FLOAT                   image mixup (probability)  [default: 0.0]
  --copy-paste FLOAT              segment copy-paste (probability)  [default:
                                  0.0]
  --dataset-path TEXT             Path to override default dataset path.
  --help                          Show this message and exit.
```

Note: This change must also be cherry-picked over to `release/1.5` branch

Note: the max torch version was updated to `<1.14`  as the after 1.13.1 next torch version on pypi is `2.0.0` https://pypi.org/project/torch/#history 

NOTE: Failing keras tests are set for removal in #1596 and #1595

### CODE REVIEW

**Comment by dhuangnm** [comment]
Thanks Rahul. Can we also fix the other error in the command output?

ERROR - 429 Client Error: Too Many Requests for url: http://ipinfo.io/96.89.198.177/json

**Comment by rahul-tuli** [comment]
> Thanks Rahul. Can we also fix the other error in the command output?
> 
> ERROR - 429 Client Error: Too Many Requests for url: http://ipinfo.io/96.89.198.177/json

@dhuangnm could you create a ticket for that error, will fix it in a separate PR as it's unrelated to this Bug, that error is from `sparsezoo.analytics`

**Comment by dhuangnm** [comment]
> > Thanks Rahul. Can we also fix the other error in the command output?
> > ERROR - 429 Client Error: Too Many Requests for url: http://ipinfo.io/96.89.198.177/json
> 
> @dhuangnm could you create a ticket for that error, will fix it in a separate PR as it's unrelated to this Bug, that error is from `sparsezoo.analytics`

Sure Rahul, filed this ticket to track the other error: https://app.asana.com/0/1203146234476221/1204662525860093/f

**Review by markurtz — DISMISSED** [review]

**Review by mgoin — APPROVED** [review]
thank you!

**Comment by dhuangnm** [comment]
Can we land this since it's already cherry-picked to 1.5?

**Comment by rahul-tuli** [comment]
The failing integration tests are green on my local system after `https://github.com/neuralmagic/sparseml/pull/1592`

**Review by markurtz — APPROVED** [review]

**Pull request merged**
