### PR TITLE
Freeze setuptools at 59.5.0

### PR DESCRIPTION
**Pull request by corey-nm**
To address issue discussed in https://github.com/pytorch/pytorch/issues/69894#issuecomment-1080635462

### CODE REVIEW

**Review by bfineran — COMMENTED** [review]
Can we add a more generic dependency rather than pinning?

**Comment by rahul-tuli** [comment]
I agree with Ben!

**Comment by corey-nm** [comment]
Sure I can make `<=59.5.0`

**Review by rahul-tuli — APPROVED** [review]
LGTM! As a side note could we also check if a later/latest version of setup tools fixes the bug.

**Comment by corey-nm** [comment]
> LGTM! As a side note could we also check if a later/latest version of setup tools fixes the bug.

The issue started with setuptools==59.6.0. It's fixed in later pytorch versions

**Review by KSGulin — APPROVED** [review]

**Pull request merged**
