### PR TITLE
[Fix] Onnxruntime-gpu install not compatible

### PR DESCRIPTION
**Pull request by dbogunowicz**
Related to issue: https://github.com/neuralmagic/sparseml/issues/704

### CODE REVIEW

**Comment by dbogunowicz** [comment]
Converting back to draft, found that this silently breaks onnx and transformer tests. Working on a solution.

**Review by bfineran — APPROVED** [review]
LGTM, any reason this was moved to a draft?

**Comment by dbogunowicz** [comment]
> LGTM, any reason this was moved to a draft?

@bfineran yeah, I did not get a chance to run some manual sanity check if this really works.
Just tested by creating a fresh venv, installing only `onnxruntime-gpu` and then running `python setup.py install`.

image

Looking good.

**Review by bfineran — CHANGES_REQUESTED** [review]
blocking this for now since as discussed offline this will not address the issue for a prebuilt wheel

**Comment by dbogunowicz** [comment]
Closing, replaced by #789.

**Pull request closed without merging**
