### PR TITLE
Option to eval w/o amp during training

### PR DESCRIPTION
**Pull request by natuan**
The evaluation in transformers currently still runs with fp16 during QAT even though this mode is turned off. This creates bigger gap in accuracy compared to deepsparse, especially for small datasets such as SST2. This PR is to provide the option `--no_amp_eval` to disable mixed precision during evaluation (default False for not affecting existing training commands).
Qualification: used the flag during QAT and separate evaluation, checked use_amp status, checked model accuracy w/ vs w/o the flag.

### CODE REVIEW

**Review by dbogunowicz — COMMENTED** [review]
Looking good @natuan , could you provide short manual testing example in the PR description?

**Comment by natuan** [comment]
> Looking good @natuan , could you provide short manual testing example in the PR description?

Updated with testing

**Review by bfineran — COMMENTED** [review]
LGTM overall. discussed this with @anmarques yesterday, but what are your thoughts on making no amp eval the default behavior for consistency then providing an option to disable the disable

**Review by bfineran — COMMENTED** [review]
can we keep in an arg to disable this? I don't think we'd need to do fp16 eval, but since this is transformers default, we should probably allow it?

**Comment by natuan** [comment]
> can we keep in an arg to disable this? I don't think we'd need to do fp16 eval, but since this is transformers default, we should probably allow it?

There's already the option from transformers `fp16_full_eval` for that purpose

**Comment by bfineran** [comment]
awesome, and that overrides these changes?

**Comment by natuan** [comment]
> awesome, and that overrides these changes?

**Comment by natuan** [comment]
> > awesome, and that overrides these changes?

Good catch. I've updated the code to take existing flags into account

**Review by rahul-tuli — APPROVED** [review]

**Review by corey-nm — APPROVED** [review]

**Pull request merged**
