### PR TITLE
Add: Sparsification + Quantization Recipes for YOLACT

### PR DESCRIPTION
**Pull request by rahul-tuli**
- yolact.pruned.md
- yolact.pruned.perf.md
- yolact.quantized.md

### CODE REVIEW

**Review by bfineran — CHANGES_REQUESTED** [review]
* the YAML recipe section should be surrounded by dashes `---` instead of underscores `___`
* where is the `module.` coming from in the recipes? is this part of the core yolact model or the DDP wrapper?

**Comment by rahul-tuli** [comment]
> * the YAML recipe section should be surrounded by dashes `---` instead of underscores `___`
> * where is the `module.` coming from in the recipes? is this part of the core yolact model or the DDP wrapper?

Good catch @bfineran; Corrected!

**Comment by markurtz** [comment]
@bfineran can you work with @rahul-tuli to paramaterize these recipes where if a user enters a different number of epochs it will shift the pruning and quantization start and ends appropriately?

**Comment by rahul-tuli** [comment]
> @bfineran can you work with @rahul-tuli to paramaterize these recipes where if a user enters a different number of epochs it will shift the pruning and quantization start and ends appropriately?

Done!

**Review by bfineran — DISMISSED** [review]
Great job on the updates, they look structurally correct to me. Let's make sure they can all be loaded into a `ScheduledModifierManager`. For the recipe composition, the pruned perf recipe is actually a block pruning recipe, so let's merge that with the quantization recipe to make a single pruned quant recipe. Looks good to land after that.

also noting that `--resume` and `--recipe` arguments should be updated with proper sparsezoo stubs

**Review by markurtz — DISMISSED** [review]

**Pull request merged**
