### PR TITLE
MatMulInteger + Add for quantized attention blocks

### PR DESCRIPTION
**Pull request by bfineran**
example block:
Screen Shot 2021-08-12 at 5 13 21 PM

### CODE REVIEW

**Comment by tlrmchlsmth** [comment]
The example graph looks great. The correction term computation looks good to me as well, although we should make sure it's well-documented, especially since these terms to handle the zero points are relatively poorly understood. 

What is your testing plan for this?

**Review by markurtz — DISMISSED** [review]
LGTM

**Comment by bfineran** [comment]
@tlrmchlsmth updated with the bias correction taken out and a `Mul` op for the cast outputs added.

immediate steps for testing will be to evaluate converted models for correctness against a standard dataset - integration testing is on the backlog for this entire script and is blocked by a few other issues.

**Review by tlrmchlsmth — APPROVED** [review]
Looks good to me!

**Review by markurtz — APPROVED** [review]

**Pull request merged**
